// This file was automatically generated from activity1.soy.
// Please don't edit this file by hand.

if (typeof adaptavant == 'undefined') { var adaptavant = {}; }
if (typeof adaptavant.fullWorkWidget == 'undefined') { adaptavant.fullWorkWidget = {}; }


adaptavant.fullWorkWidget.activityAccordion = function(opt_data, opt_ignored) {
  var output = '<!-- Activity Accordian Panel Start --><div class="panel panel-default template activity-accordian-panel" id="' + soy.$$escapeHtml(opt_data.activity.id) + '"><div class="panel-heading activity-accordion-heading padding-zero"><h4 class="panel-title"><a class="accordion-toggle" data-toggle="collapse" data-parent="#activity-accordion-group" href="#collapse-' + soy.$$escapeHtml(opt_data.activity.id) + '"><!-- Activity Info Div Starts --><div class="row info-div"><div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 padding-zero"><div class="pull-left activity-owner">Created by ' + soy.$$escapeHtml(opt_data.activity.createdBy) + '</div><div class="pull-right activity-created-on">' + soy.$$escapeHtml(opt_data.activity.createdOn) + '</div></div></div><!-- Activity Info Div Ends --><div class="activity-prof-pic"><img class="activity-prof-pic-img img-medium pull-left" src="' + ((! opt_data.activity.profilePictureUrl) ? 'img/default_prof_pic.png' : soy.$$escapeHtml(opt_data.activity.profilePictureUrl)) + '" /></div><textarea rows="1" cols="50" placeholder="Describe your activity..." class="activity-text-area old-activity-text-area pull-left" spellcheck=\'false\' id="comments-' + soy.$$escapeHtml(opt_data.activity.id) + '">' + soy.$$escapeHtml(opt_data.activity.description) + '</textarea><div  class="activity-ticking-clock" id="ticking-clock-' + soy.$$escapeHtml(opt_data.activity.id) + '"><input disabled="disabled" class="activity-ticking-clock-input" value="Wait..."/></div></a></h4></div><div id="collapse-' + soy.$$escapeHtml(opt_data.activity.id) + '" class="panel-collapse collapse activity-accordian-collapse"><div class="panel-body padding-zero"><!-- DeadLine Div Starts --><div class="row deadline-div"><div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 padding-zero"><input class="deadline-input pull-right" value="' + soy.$$escapeHtml(opt_data.activity.dueDate) + '" id="deadline-input-' + soy.$$escapeHtml(opt_data.activity.id) + '"  /></div></div><!-- DeadLine Div Ends --><!-- Tags Assisgn Div Starts --><div class="row tags-div"><div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 padding-zero"><div class="pull-left"><a href="#" class="dropdown-toggle tag-icon" data-toggle="dropdown"><div class="add-tag label pull-left">+ | Tags</div></a><ul class="dropdown-menu tag-dropdown padding-zero"><li><input placeholder="Search tag..." class="search-tag-textbox" data-provide="typeahead" autocomplete="off"></li></ul>';
  var tagList30 = opt_data.activity.tags;
  var tagListLen30 = tagList30.length;
  for (var tagIndex30 = 0; tagIndex30 < tagListLen30; tagIndex30++) {
    var tagData30 = tagList30[tagIndex30];
    output += '<div class="activity-tag label pull-left">' + soy.$$escapeHtml(tagData30.name) + '</div>';
  }
  output += '</div></div></div><!-- Tags Assisgn Div Ends --><!-- Workers List Div Starts --><div class="row workers-list-div" id="worker-list-div-' + soy.$$escapeHtml(opt_data.activity.id) + '"><div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 padding-zero"><div class="pull-left workers-list" style="width:auto;"><a href="#" class="dropdown-toggle add-worker-plus-button" data-toggle="dropdown"><div class="add-worker-plus label pull-left">+ | Watchers</div></a><ul class="dropdown-menu add-workers-dropdown padding-zero"><li><input placeholder="Search person..." style="" class="search-worker-textbox" data-provide="typeahead" autocomplete="off"></li></ul>';
  var workerList38 = opt_data.activity.workers;
  var workerListLen38 = workerList38.length;
  for (var workerIndex38 = 0; workerIndex38 < workerListLen38; workerIndex38++) {
    var workerData38 = workerList38[workerIndex38];
    output += '<div class="activity-worker label pull-left">' + soy.$$escapeHtml(workerData38.name) + '</div>';
  }
  output += '</div></div></div><!-- Workers List Div Ends --><!-- Activity Icons Div Start --><div class="row icons-div"><div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 padding-zero"><ul class="nav nav-pills pull-left icons-group"><li class="vertical-divider-right"><div class="activity-prof-pic"><img class="activity-prof-pic-img img-medium pull-left" src="' + ((! opt_data.activity.profilePictureUrl) ? 'img/default_prof_pic.png' : soy.$$escapeHtml(opt_data.activity.profilePictureUrl)) + '" /></div></li><li class="vertical-divider-right"><a href="#" class="activity-add-worker-button" style="margin: 0px 0px 0px 0px;"><img class="img-medium add-person-img" src="img/add_person.png"/></a></li><li class="vertical-divider-right"><a href="#" class="activity-tag-button"><img class="img-small" src="img/TagFliped.png"/></a></li></ul><ul class="nav nav-pills pull-right icons-group"><li><input class="activity-date-input" placeholder="" style="display:none;"/></li><li class="vertical-divider-left"><a href="#" class="activity-icons-div-date-icon"><img class="img-small" src="img/calendar-grey.png"/></a></li><li class="vertical-divider-left"><ul class="nav nav-pills icons-group"><li><a href="#" class="activity-stop-button"><img class="img-small" src="img/stop-grey.png"/></a></li><li><a href="#" class="activity-pause-button"><img class="img-small" src="img/pause-grey.png"/></a></li></ul></li><li class="vertical-divider-left"><a href="#" class="activity-play-button"><img class="img-small" src="img/Play1.png"/></a></li><li class="vertical-divider-left"><div  class="activity-ticking-clock"><input disabled="disabled" class="activity-ticking-clock-input" value="Wait..."/></div></li></ul></div></div><!-- Activity Icons Div Ends --></div></div></div><!-- Activity Accordian Panel Ends -->';
  return output;
};
